// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get("FirebaseWebAPI"),
    appId: '1:486431200794:web:9e51e16bcf3c8a8efda3a3',
    messagingSenderId: '486431200794',
    projectId: 'carlchating',
    authDomain: 'carlchating.firebaseapp.com',
    storageBucket: 'carlchating.appspot.com',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get("FirebaseAndroidAPI"),
    appId: '1:486431200794:android:b18bd6f0c1debaa8fda3a3',
    messagingSenderId: '486431200794',
    projectId: 'carlchating',
    storageBucket: 'carlchating.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.get("FirebaseIosAPI"),
    appId: '1:486431200794:ios:18b28daaad93a6c5fda3a3',
    messagingSenderId: '486431200794',
    projectId: 'carlchating',
    storageBucket: 'carlchating.appspot.com',
    iosBundleId: 'com.example.chatFlutter',
  );
}
